### ISSUE TITLE
Should 'os' be upper case?

### ISSUE THREAD

**Issue by adityaathalye** [accupara/crave#6]
The global variable is `OS`, and a check for `unknown` references this. However in-between, a variable `os` is being set to the OS type.

e.g. https://github.com/accupara/crave/blob/22312cad9e21f095a86dd4b732bf10f3c0d45dfa/get_crave.sh#L12

**Comment by adityaathalye** [comment]
Also, here, variable expansion is missing. It should be "$OS":

https://github.com/accupara/crave/blob/22312cad9e21f095a86dd4b732bf10f3c0d45dfa/get_crave.sh#L21

**Comment by uvatbc** [comment]
You're absolutely right; good catch. Fixing in a moment.

**Comment by uvatbc** [comment]
Fixed at https://github.com/accupara/crave/commit/85cc0cc4e674893e3ccab40cad8a948c231b4183
